services:
  rtcchap4persistence:
    image: rtcchap4persistence
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chap4
      - SPRING_DATASOURCE_USERNAME=chap4
      - SPRING_DATASOURCE_PASSWORD=chap4
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    develop:
      watch:
        - action: rebuild
          path: ./target/rtc-chap4-dynamodb-0.0.1-SNAPSHOT.jar
  db:
    image: postgres:16.4
    container_name: db
    environment:
      - POSTGRES_USER=chap4
      - POSTGRES_PASSWORD=chap4
      - POSTGRES_DB=chap4
    ports:
      - "5432:5432"
