services:
  rtcchap3persistence:
    image: rtcchap3persistence
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chap3
      - SPRING_DATASOURCE_USERNAME=chap3
      - SPRING_DATASOURCE_PASSWORD=chap3
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    develop:
      watch:
        - action: rebuild
          path: ./target/rtc-chap3-unit-tests-0.0.1-SNAPSHOT.jar
  db:
    image: postgres:16.4
    container_name: db
    environment:
      - POSTGRES_USER=chap3
      - POSTGRES_PASSWORD=chap3
      - POSTGRES_DB=chap3
    ports:
      - "5432:5432"
