services:
  rtcchap2persistence:
    image: rtcchap2persistence
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/local_db
      - SPRING_DATASOURCE_USERNAME=local_db
      - SPRING_DATASOURCE_PASSWORD=local_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=local_db
      - POSTGRES_PASSWORD=local_db
      - POSTGRES_DB=local_db
    ports:
      - "5432:5432"
