services:
  rtcchap2persistence:
    image: rtcchap2persistence
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chap2
      - SPRING_DATASOURCE_USERNAME=chap2
      - SPRING_DATASOURCE_PASSWORD=chap2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    develop:
      watch:
        - action: rebuild
          path: ./target/rtc-chap2-persistence-0.0.1-SNAPSHOT.jar
  db:
    image: postgres:16.4
    container_name: db
    environment:
      - POSTGRES_USER=chap2
      - POSTGRES_PASSWORD=chap2
      - POSTGRES_DB=chap2
    ports:
      - "5432:5432"
